ci: use release please

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -7,11 +7,11 @@ name: Release
 
 on:
   push:
-    tags:
-      - 'v*'
+    branches: [master]
 
 permissions:
-  contents: read
+  contents: write
+  pull-requests: write
 
 concurrency:
   group: lint-php-cs-${{ github.head_ref || github.run_id }}
@@ -20,7 +20,6 @@ concurrency:
 jobs:
   build:
     runs-on: ubuntu-latest
-
     name: Prepare Release
 
     steps:
@@ -52,93 +51,37 @@ jobs:
           name: autocurrency.tar.gz
           path: build/artifacts/appstore/nextcloud-autocurrency.tar.gz
 
-  changelog:
-    name: Update Changelog
-
+  release-please:
+    name: Release
     runs-on: ubuntu-latest
+    needs: [build]
 
     steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-
-      - name: Get Release Tags
-        run: |
-          LAST_VERSION=$(git tag --sort=version:refname | head -n 1)
-          LAST_VERSION="${LAST_VERSION#v}"
-          VERSION="${{ github.ref_name }}"
-          VERSION="${VERSION#v}"
-          echo VERSION=${VERSION} >> $GITHUB_ENV
-          echo LAST_VERSION=${LAST_VERSION} >> $GITHUB_ENV
-
-      - name: Generate changelog
-        id: changelog
-        uses: metcalfc/changelog-generator@v4
-        with:
-          myToken: ${{ secrets.GITHUB_TOKEN }}
-          base-ref: ${{ env.LAST_VERSION }}
-
-      - name: Write Changelog
-        run: |
-          LAST_VERSION="${{ env.LAST_VERSION }}"
-          VERSION="${{ env.VERSION }}"
-          cat >chlog.tmp << 'EOF'
-          ${{ steps.changelog.outputs.changelog }}
-          EOF
-          chlg="$(cat chlog.tmp)"
-          chlg="## [v$VERSION ($(date +%Y-%m-%d))](https://github.com/chenasraf/nextcloud-autocurrency/compare/v$LAST_VERSION...v$VERSION)\n\n$chlg"
-          chlg="<!--CHANGELOG-PLACEHOLDER-->\n$chlg"
-          sed -i "s|<!--CHANGELOG-PLACEHOLDER-->|${chlg}|" CHANGELOG.md
-
-      - name: Commit & Push
-        run: |
-          git config user.name "GitHub Actions"
-          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
-          git add CHANGELOG.md
-          git commit -m "chore(release): v${{ env.VERSION }}"
-
-  release:
-    name: Create Release
-
-    runs-on: ubuntu-latest
-
-    needs: [build, changelog]
-
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-
-      - name: Get Release Tag
-        run: |
-          LAST_VERSION=$(git tag --sort=version:refname | head -n 1)
-          LAST_VERSION="${LAST_VERSION#v}"
-          VERSION="${{ github.ref_name }}"
-          VERSION="${VERSION#v}"
-          echo VERSION=${VERSION} >> $GITHUB_ENV
-          echo LAST_VERSION=${LAST_VERSION} >> $GITHUB_ENV
-
-      - name: Download Artifacts
+      - name: Download builds
         uses: actions/download-artifact@v4
 
-      - name: Generate changelog
-        id: changelog
-        uses: metcalfc/changelog-generator@v4
-        with:
-          myToken: ${{ secrets.GITHUB_TOKEN }}
+      - name: Set version.txt
+        run: |
+          sudo apt-get update
+          sudo apt-get install libxml2-utils
 
-      - name: Create Release
-        uses: softprops/action-gh-release@v1
+          xmlfile="appinfo/info.xml"
+          version=$(xmllint --xpath "/info/version" appinfo/info.xml | cut -f2 -d'>' | cut -f1 -d'<')
+          if [[ -z "$version" ]]; then
+            echo "Failed to get version from $xmlfile"
+            exit 1
+          fi
+          echo "Found version: $version"
+          echo $version > version.txt
+
+      - uses: googleapis/release-please-action@v4
+        id: release
+        with:
+          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
+          release-type: simple
+
+      - name: Upload Release Artifacts
+        if: ${{ steps.release.outputs.release_created }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          name: Release ${{ github.ref_name }}
-          body: |
-            Auto Currency for Cospend Release ${{ env.VERSION }}
-
-            ## Changelog
-
-            ${{ steps.changelog.outputs.changelog }}
-
-          draft: false
-          prerelease: ${{ startsWith(github.ref_name, 'v') && (contains(github.ref, '-beta') || contains(github.ref, '-rc')) }}
-          files: |
-            autocurrency.tar.gz/autocurrency.tar.gz
+        run: gh release upload ${{ steps.release.outputs.tag_name }} autocurrency.tar.gz
